
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kadai_development

test:
  <<: *default
  database: kadai_test

production:
  <<: *default
  database: kadai_production
  username: kadai
  password: <%= ENV['KADAI_DATABASE_PASSWORD'] %>
